import './globals.css'
import Navbar from './components/navbar/Navbar'
import DarkMode from './providers/Darkmode'
import ToasterProvider from './providers/ToasterProvider'
import RegisterModal from './components/modals/RegisterModal'
import LoginModal from './components/modals/LoginModal'
import getCurrentUser from './actions/getCurrentUser'


export const metadata = {
  title: 'Blog app',
  description: 'Generated by Leopico',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en" className='light' style={{ colorScheme: 'light' }}>
      <body>
        <DarkMode>
          <ToasterProvider />
          <LoginModal />
          <RegisterModal />
          <Navbar currentUser={currentUser} />
          <div className='pb-10 pt-28 dark:bg-slate-800'>
            {children}
          </div>
        </DarkMode>
      </body>
    </html>
  )
}
